name: money_matcher
description: "An application that helps people split bills after meals."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_mlkit_text_recognition: ^0.15.0
  path: ^1.9.0
  crypto: ^3.0.3
  drift: ^2.16.0
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.1.2  # ✅ Added for local file paths
  image_picker: ^1.1.2
  fluttertoast: ^8.2.2
  intl: ^0.18.1

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  drift_dev: ^2.16.0
  build_runner: ^2.4.6
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

# 💡 Run this to generate drift files:
# flutter pub run build_runner build --delete-conflicting-outputs
